name: История Кораллово и его обитателей
title: История Кораллово и его обитателей
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  История Кораллово и его обитателей от Травина Евгения Николаевича
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: korallovo/korallovo.github.io
# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.20.2"
plugins:
  - jekyll-include-cache
include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
